apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    course: docker
    duration: 25hr
    trainer: chay
  annotations: org.docker.maintainer: chay
spec:
  containers:
  - name: nginx
    image: nginx