kind: Namespace
apiVersion: v1
metadata:
  name: roboshop   # Name Spce creation
  labels:
    name: roboshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role    # Roles creation
metadata:
  namespace: roboshop
  name: roboshop-admin-role
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding    # Attaching roles to  user which we created in IAM service
metadata:
  name: roboshop-admin-rolebinding
  namespace: roboshop
subjects:
- kind: User
  name: roboshop-admin  # User name in iam
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: roboshop-admin-role
  apiGroup: rbac.authorization.k8s.io