kind: Namespace
apiVersion: v1
metadata:
  name: roboshop   # Name Spce creation
  labels:
    name: roboshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role    # Roles creation
metadata:
  namespace: roboshop
  name: roboshop-admin-role
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding    # Attaching roles to  user which we created in IAM service
metadata:
  name: roboshop-admin-rolebinding
  namespace: roboshop
subjects:
- kind: User
  name: roboshop-admin  # User name in iam  Note :- just by maintained name k8"s will not understand this user belongs to aws iam user we need to do authentication by using this cmd - > kubectl get configmap aws-auth -n kube-system -o yaml
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: roboshop-admin-role
  apiGroup: rbac.authorization.k8s.io