apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::325196226102:role/eksctl-spot-cluster-nodegroup-spo-NodeInstanceRole-1QBZFJYG1W1Q9
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::325196226102:user/roboshop-admin
      username: roboshop-admin
    - userarn: arn:aws:iam::325196226102:user/chaitanya
      username: chaitanya     
kind: ConfigMap
metadata:
  creationTimestamp: "2023-07-30T05:47:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1117"
  uid: b70508d6-4545-4f83-8aae-5999ec3bf796